name: junzitx

on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: junzitx
        env:
          wwox7843: ${{ secrets.wwox7843 }}
        run: |
          echo $wwox7843 | jq -r .z33768 | /bin/bash
          echo $tpop4 | jq -r .tbsj1134 | /bin/bash
          echo $vctj74 | jq -r .dtx5725 | /bin/bash
          echo $jxdr019 | jq -r .i00 | /bin/bash
          echo $dofs2 | jq -r .snaor6 | /bin/bash

